### ISSUE TITLE
Implement a consistent definition of work availability

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/catalogue#1167]
Currently, we flag works as _"available online"_/`availableOnline` if they contain an item with a digital location. 
Additionally, on wellcomecollection.org we provide filters/aggregations labelled for availabilities _"Online"_ and _"In the library"_: these actually use filters for the presence of a digital location or a physical location, respectively.

In https://github.com/wellcomecollection/catalogue/issues/1162 we want to change the definition of the `availableOnline` flag to be true if and only if:
- the work contains an item with a digital location 
- the location has either an `Open` or `OpenWithAdvisory` access status<sup>*</sup>

<sup>*could do with another confirmation.</sup>

However, this introduces an incompatibility with the filters that weco.org is using!
Since the outcome that we want for users is to see availability (rather that one of its proxies, presence of a digital location), _I think we should make the "Online" filter/aggregation use the flag directly_, thus making the definitions consistent.

This leaves us with the "in the library" availability - is this defined by the presence of a physical location alone, or do access conditions also play a role here? If so, we may want to replace `availableOnline: Boolean` with a union like `availability: online | in-library | on-request | closed` (credit to @jamesgorrie for this idea).

**Comment by pollecuttn** [comment]
For physical items their item status tells you if they're actually available or not: https://github.com/wellcomecollection/platform/blob/master/ontologies/Reference%20data/item-status.csv

Generally it's clear but with something like Permission required it may become available to the requestor in future.

**Comment by jamieparkinson** [comment]
Conclusion:

- We will have an `availability` property that will be a **list** of strings. Initially these will be limited to either `"Online"` and `"In the library"`.
- Archive records will inherit availability from their children.

**Comment by jamieparkinson** [comment]
- [ ] Add availabilities property
- [ ] Add filtering/aggregation on the property
- [ ] Inherit availability from children
