### ISSUE TITLE
Add contributor filter & aggregations to API

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue#1260]

**Comment by alexwlchan** [comment]
I think this might be deployed already; I need to test it.

**Comment by warrd** [comment]
(requires a reindex, a voice said)

**Comment by warrd** [comment]
(still getting notifications for some reason)

**Comment by alexwlchan** [comment]
I think the reindex is done, I just need to test it.

Try clicking the unsubscribe button on the right?

**Comment by alexwlchan** [comment]
James has confirmed this is working.
