### ISSUE TITLE
Handle Calm record deletions

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/catalogue#1319]
We've [realised](https://wellcome.slack.com/archives/C3TQSF63C/p1611737141230300?thread_ts=1611737002.230000&cid=C3TQSF63C) that Calm record deletions are not picked up by the pipeline - this needs to be fixed!

As far as we can tell, once something is deleted it's gone for good, so our solution needs to be something along the lines of polling for deletions and flagging them in the Calm VHS so that the transformer can create the relevant `Deleted` works. 

Things to do:

- [x] Talk to collections folk and agree on an acceptable polling frequency
- [x] RFC this into something concrete
- [x] Implement it

**Comment by kenoir** [comment]
Is there absolutely positively no-way for Calm to inform us of the deletions?

**Comment by alexwlchan** [comment]
> Is there absolutely positively no-way for Calm to inform us of the deletions?

The Calm API is very not good, and poorly documented. I had another look at it today; I'm pretty sure it's not possible.

**Comment by warrd** [comment]
Some further docs in case anyone missed these: https://github.com/wellcomecollection/platform/files/4244727/Calm.API.Guide.pdf

**Comment by alexwlchan** [comment]
> We could also hijack the delete mechanism in Calm and request from collections staff that deletions are handled by a system we provide that both deletes in Calm and notifies us of the deletion.

I'm not sure we can programatically delete records from Calm. I think the API in the current version of Calm is read-only.
