### ISSUE TITLE
Image versioning should reflect changes to sources

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/catalogue#895]

**Comment by kenoir** [comment]
Can you fill out the description with some more context for this PR?

**Comment by jamieparkinson** [comment]
A lot of the work is working out exactly what the issue is and how to address it so I will do this in the PR

**Comment by jamieparkinson** [comment]
https://github.com/wellcomecollection/catalogue/pull/908

**Comment by pollecuttn** [comment]
@jamieparkinson This is in Done - if it should be closed, please close it - thanks.

**Comment by jamieparkinson** [comment]
Superseded by https://github.com/wellcomecollection/catalogue/issues/934
