### ISSUE TITLE
Post stage-release testing 

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue#898]
Currently different members across the team have different smoke tests they run before deploying to prod.

One set of tests is running the experience app against the staging API. It would be good to have these Dockerised and accessible to the whole team to help with a smoother, more confident API deployment.

This will add confidence to our releases as we add and transform a [whole load of new data into the API](https://github.com/wellcomecollection/platform/issues/4643).

This will then be available to CI where we're starting to deploy the API via CI to stage 🥳 .

After we have run some post-stage tests, we will be closer to be full Agile™ and continuously deploy to prod.

**Comment by kenoir** [comment]
Closing as done.
