### ISSUE TITLE
Write script to determine is deployment is successful for CI

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue#927]
Ref #898 

Write a script that can compare the `deployment:label` tag of a service against the tasks running within that service to determine that a service has successfully deployed.

This can then be added to the [`release to stage`](https://github.com/wellcomecollection/catalogue/blob/master/.buildkite/pipeline.yml#L68) step of the build as a "completed" check.

**Comment by kenoir** [comment]
This should be a `weco-deploy` command to keep the deployment logic together.
