### ISSUE TITLE
Healthchecks for post-stage deployment

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue#928]
Ref #898 

[After a deployment to the stage API](https://github.com/wellcomecollection/catalogue/issues/927), we should have some tests run against

* `/works`
* `/works?query={query}`
* `/works/{id}`
* `/images`
* `/images?query={query}`
* `/images/{id}`

On the front end, the following paths should be checked:

- /visit-us
- /whats-on
- /stories
- /collections
- /what-we-do 

To make sure we get 200s.

**Comment by kenoir** [comment]
Closing as done.
