### ISSUE TITLE
Ingest versioning is not consistent with respect to merging

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/catalogue#934]

**Comment by alicefuzier** [comment]
- [ ] Make METS Adapter store createdDate from the bag manifest https://github.com/wellcomecollection/catalogue/pull/946
- [ ] Update METS store to add createdDate
- [ ] Change transformers to add modifiedDate in the work
- [ ] Change merger to pick version as the highest timestamp in a gruoup of works
