### ISSUE TITLE
Catalogue API is underpowered for current request volume

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/catalogue#943]
Currently there are some situations where we can get brown-outs in the catalogue API as serving requests is causing CPU usage to MAX out.

<img width="1221" alt="Screenshot 2020-10-12 at 12 20 19" src="https://user-images.githubusercontent.com/953792/95742679-46edb080-0c88-11eb-8d33-c7e5d5da88b7.png">

This is likely caused by the release of https://github.com/wellcomecollection/wellcomecollection.org/pull/5612 - and non-optimal patterns of requests caused by a lack of denormalised data present in the API. 

This will likely be resolved by https://github.com/wellcomecollection/platform/issues/4673

**Solution:** 

- [x] The catalogue API instances are underpowered (0.5 vCPU, 1GB memory), we could probably get away with x2 without significant relative cost increase. (https://github.com/wellcomecollection/catalogue/issues/943)
- [x] Temporarily reduce load on the API by reducing request volume. (https://github.com/wellcomecollection/wellcomecollection.org/issues/5616)

**Comment by jamesgorrie** [comment]
@kenoir you happy with this?
