### ISSUE TITLE
Missing archive level PP/EKC/B

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/catalogue#952]
Feedback from Eoin in Research that there's a level missing from this archive collection: https://wellcomecollection.org/works/jnwyc38x. There should be a PP/EKC/B in the tree. 
(https://wellcome.slack.com/archives/C016UC43VEH/p1602598038002300)

The archive tree is correct in CALM: http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=0&dsqSearch=%28AltRefNo%3D%27PP%2FEKC%2FB%27%29

**Comment by jtweed** [comment]
We're also seeing this on several of the sections within PP/AMI.

**Comment by warrd** [comment]
The `PP/EKC/B` is now showing in the tree. The `PP/AMI` archives appear to all be marked as supressed, so are not coming up in the API.

**Comment by pollecuttn** [comment]
@warrd https://wellcomecollection.org/works/dw67bv4q is the collection level work for PP/AMI, so that's showing but there's no archive tree. Is it the rest of the archive that's suppressed, but just not this somehow?

**Comment by jtweed** [comment]
Appears to be the case, looking at archives.wellcomelibrary.org.
